### ISSUE TITLE
phar file: Call to undefined function

### ISSUE THREAD

**Issue by FlorentPaillot** [llaville/php-compat-info#214] opened 2015-12-21 01:51 UTC
I have downloaded the phar file v5.0.0 and ran "php phpcompatinfo-5.0.0.phar --version" and got the following error message:

     PHP Fatal error:  Call to undefined function Bartlett\Reflect\Console\fnmatch() in phar:///volume1/web/lib/test/phpcompatinfo-5.0.0.phar/vendor/bartlett/php-reflect/src/Bartlett/Reflect/Console/CommandFactory.php on line 84

     Fatal error: Call to undefined function Bartlett\Reflect\Console\fnmatch() in phar:///volume1/web/lib/test/phpcompatinfo-5.0.0.phar/vendor/bartlett/php-reflect/src/Bartlett/Reflect/Console/CommandFactory.php on line 84

I got the same error message when running the 4.5.2 version.

**Comment by llaville** [comment] 2015-12-21 21:51
Sorry, but I can't reproduced this issue: 
I got this output with PHP 5.6.16
```
phpcompatinfo-4.5.2.phar --version
phpCompatInfo version 4.5.2 DB built Nov 21 2015 10:11:06 CET

phpcompatinfo-5.0.0.phar --version
phpCompatInfo version 5.0.0 DB built Dec 04 2015 21:00:36 CET
```

**Comment by llaville** [comment] 2016-02-05 21:56
No feedback. I close this issue

**Closed by llaville** 2016-02-05 21:56 UTC

**Comment by FlorentPaillot** [comment] 2016-02-08 02:19
Hi,

Sorry for the late reply. The problem was related to a missing extension. I had
to wait until I could update the server (A Synology NAS) to get that missing
extension.

Regards,
Florent

On Sat, Feb 06, 2016 at 8:26 AM, Laurent Laville < notifications@github.com [notifications@github.com] > wrote:
No feedback. I close this issue

—
Reply to this email directly or view it on GitHub
[https://github.com/llaville/php-compat-info/issues/214#issuecomment-180582396] .[https://github.com/notifications/beacon/AM4bAve1oAVtyfgrI739PlMgHIprw33Bks5phRIXgaJpZM4G48zO.gif]
